Lists cards fixes
jonevanmoore/jello pull request #112
Opened 2022-05-07 21:25 UTC by danguai

2022-05-07 21:27 UTC, MasonKogami approved these changes

2022-05-07 22:45 UTC, jonevanmoore approved these changes

2022-05-07 23:01 UTC, Nick-Yawn approved these changes

2022-05-07 23:04 UTC, Nick-Yawn requested changes
Card title edit styling,
Card title edit button double-click
Description add / edit button text

2022-05-08 00:11 UTC, Nick-Yawn approved these changes

2022-05-08 00:12 UTC, jonevanmoore approved these changes

2022-05-08 00:13 UTC, merged