Backend BOARDS Create, Read
jonevanmoore/jello pull request #39
Opened 2022-05-02 19:45 UTC by danguai

2022-05-02 20:07 UTC, jonevanmoore submitted a review, later dismissed

2022-05-03 16:12 UTC, MasonKogami approved these changes

2022-05-03 16:16 UTC, Nick-Yawn requested changes, later dismissed

2022-05-03 16:16 UTC, Nick-Yawn commented on migrations/versions/20220502_171842_boards_table.py
> +    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
I think this line needs an onupdate flag

2022-05-03 16:17 UTC, Nick-Yawn commented on migrations/versions/20220502_171842_boards_table.py
> +    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
```
time_created = Column(DateTime(timezone=True), server_default=func.now())
time_updated = Column(DateTime(timezone=True), onupdate=func.now())
```

2022-05-03 16:23 UTC, Nick-Yawn approved these changes

2022-05-03 16:23 UTC, jonevanmoore approved these changes

2022-05-03 16:25 UTC, Nick-Yawn requested changes
boards FK

2022-05-03 21:31 UTC, Nick-Yawn approved these changes

2022-05-03 22:15 UTC, Nick-Yawn requested changes
merge main

2022-05-03 22:19 UTC, Nick-Yawn approved these changes

2022-05-03 22:20 UTC, merged