splash page looking good. May have to adjust some positions when navb…
jonevanmoore/jello pull request #44
Opened 2022-05-03 17:42 UTC by jonevanmoore

…ar is remove
<img width="1440" alt="Screen Shot 2022-05-03 at 12 41 27 PM" src="https://user-images.githubusercontent.com/64309316/166509008-fdfc4c67-3cda-47bd-9309-533dbd710eda.png">
d

2022-05-03 18:43 UTC, Nick-Yawn requested changes
Looks excellent! I'm really stoked on how close it is to the wireframes!!!

2022-05-03 18:43 UTC, Nick-Yawn commented on frontend/src/components/LandingPage/LandingPage.js
> +                        <img src='/logo-dark.png' className='dark-logo' />
The source here will need to be changed to `static/logo-dark.png` — this is currently broken in production.

2022-05-03 18:43 UTC, Nick-Yawn commented on frontend/src/components/LandingPage/LandingPage.js
> +                            <img src="/jello9.png" className="coder-img jello-wiggle"></img>
Similarly, I believe these files should be moved back into `/public/static/`, and the sources changed to match.

2022-05-03 18:44 UTC, Nick-Yawn commented on frontend/src/components/LandingPage/LandingPage.js
> +                        <img src='/logo-dark.png' className='dark-logo' />
Oh, and the `logo-dark.png` will also have to be moved into `static/`

2022-05-04 15:07 UTC, MasonKogami approved these changes

2022-05-04 15:07 UTC, Nick-Yawn approved these changes

2022-05-04 15:08 UTC, merged